png("plot3.png")
plot(power$DateTime, power$Sub_metering_1, type = 'n', xlab = '', ylab = 'Energy Sub metering', cex.axis = .8, cex.lab = .75)
lines(power$DateTime, power$Sub_metering_1, col = 'black')
lines(power$DateTime, power$Sub_metering_2, col = 'red')
lines(power$DateTime, power$Sub_metering_3, col = 'blue')
legend('topright', legend = c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), lty = c(1, 1, 1), col = c('black', 'red', 'blue'), cex = .8)
dev.off()